# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attempt1.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_startstop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_startstop.setGeometry(QtCore.QRect(20, 20, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_startstop.setFont(font)
        self.btn_startstop.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_startstop.setMouseTracking(False)
        self.btn_startstop.setCheckable(False)
        self.btn_startstop.setAutoDefault(False)
        self.btn_startstop.setDefault(False)
        self.btn_startstop.setFlat(False)
        self.btn_startstop.setObjectName("btn_startstop")
        self.btn_browse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_browse.setGeometry(QtCore.QRect(240, 130, 81, 31))
        self.btn_browse.setObjectName("btn_browse")
        self.ed_saveloc = QtWidgets.QLineEdit(self.centralwidget)
        self.ed_saveloc.setEnabled(False)
        self.ed_saveloc.setGeometry(QtCore.QRect(20, 130, 211, 31))
        self.ed_saveloc.setObjectName("ed_saveloc")
        self.groupe_timeseries = QtWidgets.QGroupBox(self.centralwidget)
        self.groupe_timeseries.setGeometry(QtCore.QRect(20, 170, 521, 701))
        self.groupe_timeseries.setObjectName("groupe_timeseries")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupe_timeseries)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 501, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tsgraph_el1 = PlotWidget(self.verticalLayoutWidget)
        self.tsgraph_el1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tsgraph_el1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tsgraph_el1.setObjectName("tsgraph_el1")
        self.verticalLayout.addWidget(self.tsgraph_el1)
        self.tsgraph_el2 = PlotWidget(self.verticalLayoutWidget)
        self.tsgraph_el2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tsgraph_el2.setObjectName("tsgraph_el2")
        self.verticalLayout.addWidget(self.tsgraph_el2)
        self.tsgraph_el3 = PlotWidget(self.verticalLayoutWidget)
        self.tsgraph_el3.setObjectName("tsgraph_el3")
        self.verticalLayout.addWidget(self.tsgraph_el3)
        self.tsgraph_el4 = PlotWidget(self.verticalLayoutWidget)
        self.tsgraph_el4.setObjectName("tsgraph_el4")
        self.verticalLayout.addWidget(self.tsgraph_el4)
        self.group_frequencyspectrums = QtWidgets.QGroupBox(self.centralwidget)
        self.group_frequencyspectrums.setGeometry(QtCore.QRect(660, 170, 521, 701))
        self.group_frequencyspectrums.setObjectName("group_frequencyspectrums")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.group_frequencyspectrums)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 19, 501, 671))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fsgraph_el1 = PlotWidget(self.verticalLayoutWidget_2)
        self.fsgraph_el1.setObjectName("fsgraph_el1")
        self.verticalLayout_2.addWidget(self.fsgraph_el1)
        self.fsgraph_el2 = PlotWidget(self.verticalLayoutWidget_2)
        self.fsgraph_el2.setObjectName("fsgraph_el2")
        self.verticalLayout_2.addWidget(self.fsgraph_el2)
        self.fsgraph_el3 = PlotWidget(self.verticalLayoutWidget_2)
        self.fsgraph_el3.setObjectName("fsgraph_el3")
        self.verticalLayout_2.addWidget(self.fsgraph_el3)
        self.fsgraph_el4 = PlotWidget(self.verticalLayoutWidget_2)
        self.fsgraph_el4.setObjectName("fsgraph_el4")
        self.verticalLayout_2.addWidget(self.fsgraph_el4)
        self.group_el1 = QtWidgets.QGroupBox(self.centralwidget)
        self.group_el1.setGeometry(QtCore.QRect(550, 200, 101, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.group_el1.setFont(font)
        self.group_el1.setMouseTracking(False)
        self.group_el1.setAlignment(QtCore.Qt.AlignCenter)
        self.group_el1.setFlat(False)
        self.group_el1.setCheckable(True)
        self.group_el1.setChecked(True)
        self.group_el1.setObjectName("group_el1")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.group_el1)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 19, 91, 101))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.vlay_el1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.vlay_el1.setContentsMargins(0, 0, 0, 0)
        self.vlay_el1.setObjectName("vlay_el1")
        self.rbnormal_el1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.rbnormal_el1.setFont(font)
        self.rbnormal_el1.setChecked(True)
        self.rbnormal_el1.setObjectName("rbnormal_el1")
        self.vlay_el1.addWidget(self.rbnormal_el1)
        self.rbalpha_el1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.rbalpha_el1.setFont(font)
        self.rbalpha_el1.setObjectName("rbalpha_el1")
        self.vlay_el1.addWidget(self.rbalpha_el1)
        self.rbcustom_el1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.rbcustom_el1.setFont(font)
        self.rbcustom_el1.setObjectName("rbcustom_el1")
        self.vlay_el1.addWidget(self.rbcustom_el1)
        self.group_el2 = QtWidgets.QGroupBox(self.centralwidget)
        self.group_el2.setGeometry(QtCore.QRect(550, 370, 101, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.group_el2.setFont(font)
        self.group_el2.setMouseTracking(False)
        self.group_el2.setAlignment(QtCore.Qt.AlignCenter)
        self.group_el2.setFlat(False)
        self.group_el2.setCheckable(True)
        self.group_el2.setChecked(True)
        self.group_el2.setObjectName("group_el2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.group_el2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 91, 101))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.vlay_el2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.vlay_el2.setContentsMargins(0, 0, 0, 0)
        self.vlay_el2.setObjectName("vlay_el2")
        self.rbnormal_el2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbnormal_el2.setFont(font)
        self.rbnormal_el2.setChecked(True)
        self.rbnormal_el2.setObjectName("rbnormal_el2")
        self.vlay_el2.addWidget(self.rbnormal_el2)
        self.rbalpha_el2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.rbalpha_el2.setFont(font)
        self.rbalpha_el2.setObjectName("rbalpha_el2")
        self.vlay_el2.addWidget(self.rbalpha_el2)
        self.rbcustom_el2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.rbcustom_el2.setFont(font)
        self.rbcustom_el2.setObjectName("rbcustom_el2")
        self.vlay_el2.addWidget(self.rbcustom_el2)
        self.group_el3 = QtWidgets.QGroupBox(self.centralwidget)
        self.group_el3.setGeometry(QtCore.QRect(550, 540, 101, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.group_el3.setFont(font)
        self.group_el3.setMouseTracking(False)
        self.group_el3.setAlignment(QtCore.Qt.AlignCenter)
        self.group_el3.setFlat(False)
        self.group_el3.setCheckable(True)
        self.group_el3.setChecked(True)
        self.group_el3.setObjectName("group_el3")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.group_el3)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 91, 101))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.vlay_el3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.vlay_el3.setContentsMargins(0, 0, 0, 0)
        self.vlay_el3.setObjectName("vlay_el3")
        self.rbnormal_el3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.rbnormal_el3.setFont(font)
        self.rbnormal_el3.setChecked(True)
        self.rbnormal_el3.setObjectName("rbnormal_el3")
        self.vlay_el3.addWidget(self.rbnormal_el3)
        self.rbalpha_el3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.rbalpha_el3.setFont(font)
        self.rbalpha_el3.setObjectName("rbalpha_el3")
        self.vlay_el3.addWidget(self.rbalpha_el3)
        self.rbcustom_el3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.rbcustom_el3.setFont(font)
        self.rbcustom_el3.setObjectName("rbcustom_el3")
        self.vlay_el3.addWidget(self.rbcustom_el3)
        self.group_el4 = QtWidgets.QGroupBox(self.centralwidget)
        self.group_el4.setGeometry(QtCore.QRect(550, 710, 101, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.group_el4.setFont(font)
        self.group_el4.setMouseTracking(False)
        self.group_el4.setAlignment(QtCore.Qt.AlignCenter)
        self.group_el4.setFlat(False)
        self.group_el4.setCheckable(True)
        self.group_el4.setChecked(True)
        self.group_el4.setObjectName("group_el4")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.group_el4)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 91, 101))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.vlay_el4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.vlay_el4.setContentsMargins(0, 0, 0, 0)
        self.vlay_el4.setObjectName("vlay_el4")
        self.rbnormal_el4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.rbnormal_el4.setFont(font)
        self.rbnormal_el4.setChecked(True)
        self.rbnormal_el4.setObjectName("rbnormal_el4")
        self.vlay_el4.addWidget(self.rbnormal_el4)
        self.rbalpha_el4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.rbalpha_el4.setFont(font)
        self.rbalpha_el4.setObjectName("rbalpha_el4")
        self.vlay_el4.addWidget(self.rbalpha_el4)
        self.rbcustom_el4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.rbcustom_el4.setFont(font)
        self.rbcustom_el4.setObjectName("rbcustom_el4")
        self.vlay_el4.addWidget(self.rbcustom_el4)
        self.lab_logo = QtWidgets.QLabel(self.centralwidget)
        self.lab_logo.setGeometry(QtCore.QRect(1020, 0, 161, 171))
        self.lab_logo.setObjectName("lab_logo")
        self.group_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.group_tab.setGeometry(QtCore.QRect(330, 10, 691, 151))
        self.group_tab.setObjectName("group_tab")
        self.tab_set = QtWidgets.QWidget()
        self.tab_set.setObjectName("tab_set")
        self.group_tab.addTab(self.tab_set, "")
        self.tab_cmode = QtWidgets.QWidget()
        self.tab_cmode.setObjectName("tab_cmode")
        self.group_tab.addTab(self.tab_cmode, "")
        self.tab_acq = QtWidgets.QWidget()
        self.tab_acq.setObjectName("tab_acq")
        self.group_tab.addTab(self.tab_acq, "")
        self.tab_sp = QtWidgets.QWidget()
        self.tab_sp.setObjectName("tab_sp")
        self.group_tab.addTab(self.tab_sp, "")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setObjectName("tab_info")
        self.group_tab.addTab(self.tab_info, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.group_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_startstop, self.btn_browse)
        MainWindow.setTabOrder(self.btn_browse, self.ed_saveloc)
        MainWindow.setTabOrder(self.ed_saveloc, self.tsgraph_el1)
        MainWindow.setTabOrder(self.tsgraph_el1, self.tsgraph_el2)
        MainWindow.setTabOrder(self.tsgraph_el2, self.tsgraph_el4)
        MainWindow.setTabOrder(self.tsgraph_el4, self.fsgraph_el1)
        MainWindow.setTabOrder(self.fsgraph_el1, self.fsgraph_el2)
        MainWindow.setTabOrder(self.fsgraph_el2, self.fsgraph_el3)
        MainWindow.setTabOrder(self.fsgraph_el3, self.fsgraph_el4)
        MainWindow.setTabOrder(self.fsgraph_el4, self.group_el1)
        MainWindow.setTabOrder(self.group_el1, self.rbnormal_el1)
        MainWindow.setTabOrder(self.rbnormal_el1, self.rbalpha_el1)
        MainWindow.setTabOrder(self.rbalpha_el1, self.rbcustom_el1)
        MainWindow.setTabOrder(self.rbcustom_el1, self.group_el2)
        MainWindow.setTabOrder(self.group_el2, self.group_el3)
        MainWindow.setTabOrder(self.group_el3, self.rbnormal_el2)
        MainWindow.setTabOrder(self.rbnormal_el2, self.rbalpha_el2)
        MainWindow.setTabOrder(self.rbalpha_el2, self.rbcustom_el2)
        MainWindow.setTabOrder(self.rbcustom_el2, self.group_el4)
        MainWindow.setTabOrder(self.group_el4, self.rbnormal_el3)
        MainWindow.setTabOrder(self.rbnormal_el3, self.rbalpha_el3)
        MainWindow.setTabOrder(self.rbalpha_el3, self.rbcustom_el3)
        MainWindow.setTabOrder(self.rbcustom_el3, self.rbnormal_el4)
        MainWindow.setTabOrder(self.rbnormal_el4, self.rbalpha_el4)
        MainWindow.setTabOrder(self.rbalpha_el4, self.rbcustom_el4)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_startstop.setText(_translate("MainWindow", "START"))
        self.btn_browse.setText(_translate("MainWindow", "Browse"))
        self.ed_saveloc.setText(_translate("MainWindow", "Save location"))
        self.groupe_timeseries.setTitle(_translate("MainWindow", "Time Series Graph"))
        self.group_frequencyspectrums.setTitle(_translate("MainWindow", "Frequency Spectrums"))
        self.group_el1.setTitle(_translate("MainWindow", "Electrode 1"))
        self.rbnormal_el1.setText(_translate("MainWindow", "Normal Mode"))
        self.rbalpha_el1.setText(_translate("MainWindow", "Alpha Mode"))
        self.rbcustom_el1.setText(_translate("MainWindow", "Custom Mode"))
        self.group_el2.setTitle(_translate("MainWindow", "Electrode 2"))
        self.rbnormal_el2.setText(_translate("MainWindow", "Normal Mode"))
        self.rbalpha_el2.setText(_translate("MainWindow", "Alpha Mode"))
        self.rbcustom_el2.setText(_translate("MainWindow", "Custom Mode"))
        self.group_el3.setTitle(_translate("MainWindow", "Electrode 3"))
        self.rbnormal_el3.setText(_translate("MainWindow", "Normal Mode"))
        self.rbalpha_el3.setText(_translate("MainWindow", "Alpha Mode"))
        self.rbcustom_el3.setText(_translate("MainWindow", "Custom Mode"))
        self.group_el4.setTitle(_translate("MainWindow", "Electrode 4"))
        self.rbnormal_el4.setText(_translate("MainWindow", "Normal Mode"))
        self.rbalpha_el4.setText(_translate("MainWindow", "Alpha Mode"))
        self.rbcustom_el4.setText(_translate("MainWindow", "Custom Mode"))
        self.lab_logo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"logo_plein.png\"/></p></body></html>"))
        self.group_tab.setTabText(self.group_tab.indexOf(self.tab_set), _translate("MainWindow", "Display settings"))
        self.group_tab.setTabText(self.group_tab.indexOf(self.tab_cmode), _translate("MainWindow", "Custom Mode settings"))
        self.group_tab.setTabText(self.group_tab.indexOf(self.tab_acq), _translate("MainWindow", "Acquisition settings"))
        self.group_tab.setTabText(self.group_tab.indexOf(self.tab_sp), _translate("MainWindow", "Signal Processing settings"))
        self.group_tab.setTabText(self.group_tab.indexOf(self.tab_info), _translate("MainWindow", "Acquisition Information"))

from pyqtgraph import PlotWidget

